CREATE TABLE "DBA"."HISTO_HUELLAS" (
	"HISTO_ID" INTEGER NOT NULL DEFAULT AUTOINCREMENT UNIQUE,
	"HISTO_TABLA" VARCHAR(50) NULL,
	"HISTO_IDENTIFICADOR" VARCHAR(100) NULL,
	"HISTO_CAMPO" VARCHAR(50) NULL,
	"HISTO_VANTERIOR" VARCHAR(800) NULL,
	"HISTO_VACTUAL" VARCHAR(800) NULL,
	"HISTO_ACCION" CHAR(20) NULL,
	"HISTO_USR_ACCION" VARCHAR(50) NULL,
	"HISTO_FECHA_ACCION" TIMESTAMP NULL DEFAULT CURRENT TIMESTAMP,
	"HISTO_INFO_ADICIONAL" VARCHAR(500) NULL,
	"HISTO_OBSERVACION" VARCHAR(500) NULL,
	PRIMARY KEY ( "HISTO_ID" ASC )
) IN "system";
COMMENT ON TABLE "DBA"."HISTO_HUELLAS" IS 'HISTORICO EN CASO DE BORRAR HUELLAS';
COMMENT ON COLUMN "DBA"."HISTO_HUELLAS"."HISTO_TABLA" IS 'TABLA DEL MODULO DE HUELLAS AFECTADO';
COMMENT ON COLUMN "DBA"."HISTO_HUELLAS"."HISTO_IDENTIFICADOR" IS 'identificador de la fila afectada';
COMMENT ON COLUMN "DBA"."HISTO_HUELLAS"."HISTO_CAMPO" IS 'CAMPO DE ALGUNA TABLA AFECTADA';
COMMENT ON COLUMN "DBA"."HISTO_HUELLAS"."HISTO_VANTERIOR" IS 'VALOR ANTERIOR DE ESA TABLA';
COMMENT ON COLUMN "DBA"."HISTO_HUELLAS"."HISTO_VACTUAL" IS 'VALOR ACTUAL TRAS LA ACCION DE UPDATE';
COMMENT ON COLUMN "DBA"."HISTO_HUELLAS"."HISTO_ACCION" IS 'ACCION REALIZADA';
COMMENT ON COLUMN "DBA"."HISTO_HUELLAS"."HISTO_USR_ACCION" IS 'USAURIO QUE REALIZO LA ACCION';
COMMENT ON COLUMN "DBA"."HISTO_HUELLAS"."HISTO_FECHA_ACCION" IS 'FECHA EN QUE SE REALIZO LA ACCION ';
COMMENT ON COLUMN "DBA"."HISTO_HUELLAS"."HISTO_INFO_ADICIONAL" IS 'INFORMACION ADICIONAL (DEL EQUIPO)';
COMMENT ON COLUMN "DBA"."HISTO_HUELLAS"."HISTO_OBSERVACION" IS 'en caso de eliminacion de una huella debera ir la justificacion';
